version: '3.3'
services:
  mysql:
    container_name: db
    image: docker.io/mysql:8.0
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - ./script:/docker-entrypoint-initdb.d/
      - ./mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: abc123

  backend:
    container_name: backend
    image: quay.io/chisanuchakim/oasip-sy-5-backend
    restart: on-failure
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    links:
      - mysql

  frontend:
    image: quay.io/chisanuchakim/oasip-sy-5-fontend
    container_name: frontend
    ports:
      - "80:80"
      

