name: timeup-runner

on:
  push:
    branches: [ dev ]
    
jobs:
  build:

    runs-on: self-hosted

#     strategy:
#       matrix:
#         node-version: [12.x, 14.x, 16.x]
#         # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - run: docker-compose down
    - run: docker ps
    - run: docker image rmi quay.io/chisanuchakim/oasip-sy-5-backend  quay.io/chisanuchakim/oasip-sy-5-fontend frontend backend
    - run: cd TimeUpBackedn
    - run: docker build -t backend -f backend.Dockerfile .
    - run: docker tag backend quay.io/chisanuchakim/oasip-sy-5-backend
    - run: docker push quay.io/chisanuchakim/oasip-sy-5-backend
    - run: cd ../
    - run: cd TimeupFrontend
    - run: docker build -t frontend .
    - run: docker tag frontend quay.io/chisanuchakim/oasip-sy-5-fontend
    - run: docker push quay.io/chisanuchakim/oasip-sy-5-fontend
    - run: docker-compose up -d 
